#spring 配置
spring:
  messages:
    #国际化配置
    basename: i18n.login
  thymeleaf:
    #thymeleaf 页面缓存
    cache: false
  mvc:
    #日期格式化
    date-format: yyy-MM-dd
    static-path-pattern: /static/**
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    #druid 连接池
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #redis
  redis:
    database: 0
    host: 49.235.206.214
    port: 6379
    timeout: 6000
    password:

#server 服务配置
server:
  port: 8081

#log 日志配置
logging:
  level:
    root: debug
#  file:
#    /shopping-mall-test.log

#mp 配置
mybatis-plus:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #缓存是否开启
    cache-enabled: false
  mapper-locations: classpath:/mapper/*Mapper.xml
